TWITTER_KEY: '3JMFWT7JrdjtCFEOG1CfA'
TWITTER_SECRET: 'bnbZDLJHzD1EZ2fSXIjxQJ4ANaZ6aFPgn5Kg7ZwZslI'
OAUTH_TOKEN: '1920482970-mjQruTSMhDnHVeqXuRTvgJkR25BHXQrnxj6Pq6B'
OAUTH_TOKEN_SECRET: 'ZgjRL2g3JjhhzVxE0fRswx9fKlLi9f8FrgQrc5AqcDQ'
